version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: order_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - ordernet
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: order_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - ordernet

    mysql:
        image: mysql:8
        container_name: order_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: order
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - order_mysql_data:/var/lib/mysql
        networks:
            - ordernet
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: order_phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
        networks:
            - ordernet


networks:
    ordernet:

volumes:
    order_mysql_data:
